### ISSUE TITLE
issues with binary messages

### ISSUE THREAD

**Issue by marcobrianza** [256dpi/processing-mqtt#8]
Hello, and thank you for the very nice MQTT framework you have developed.
Consider I'm new to MQTT so what I'm writing might miss some basic information :-)

I'm doing some tests both with Processing and Arduino (using ESP8266)
My intention is to transmit a 3 byte binary payload.
I have upload my code in this repo: https://github.com/marcobrianza/wemakecolors/blob/master/Processing/testMQTT/testMQTT.pde

I made some tests both with shiftr and mosquitto server and I see a different behaviour:
The issue happens if I send a binary value above 127.
With shiftr server the subscriber receives a message of 5 byes instead of 3.
With mosquitto the message is of 3 bytes, but the byte is wrong.

This makes me think that there is something wrong both on the shiftr server and the lib.

With Arduino the problem is similar, but I could not  find a way to connect to test.mosquitto.org so cannot see if the lib is correct in this case.

thank you
Marco

**Comment by 256dpi** [comment]
Hi Marco thanks for raising this!

In fact you uncovered a bug in shiftr.io as it seems that it does not handle binary payloads properly. The backend converts the incoming byte array to a string at some point where it also might get converted to UTF16, which would explain the growing size. I’m about to replace the backend soon, that way the problem will go away automatically.

On the other hand you also uncovered and ugly truth about Java:
http://stackoverflow.com/questions/11088/what-is-the-best-way-to-work-around-the-fact-that-all-java-bytes-are-signed

In Java all number primitives are signed, that means 128 is actually -128. In order to get the real values, you need to convert the incoming bytes accordingly:

``` java
import mqtt.*;
import java.util.*;

MQTTClient client;

void setup() {
  client = new MQTTClient(this);
  client.connect("mqtt://localhost", "processing");
  client.subscribe("/hello");
  // client.unsubscribe("/example");
}

void draw() {}

void keyPressed() {
  color cc = color(127, 128, 255);

  byte[] c = new byte[3];
  c[0]=byte(red(cc));
  c[1]=byte(green(cc));
  c[2]=byte(blue(cc));

  client.publish("/hello", c);
}

void messageReceived(String topic, byte[] payload) {
  println(payload.length);
  println("new message: " + topic + " - " + Arrays.toString(payload));
}

int[] convert(byte[] in) {
  int[] out = new int[in.length];

  for(int i=0; i<in.length; i++) {
    out[i] = in[i] & 0xff; // <- convert back
  }

  return out;
}
```

In that sense the library is correct and should work at least with mosquitto.

I'll fix the bug in shiftr.io as soon as possible, in the mean time you could just write the colors as strings `127,128,255` and convert them back in processing using `Integer.parseInt(value)` or something similar. In my projects I always favor this method as then the shiftr.io graph and console will show human readable values rather than symbols and bytes.

All the Best!
